//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by klog.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_TRAYICON                    101
#define IDD_KLOG_DIALOG                 102
#define IDS_LOGTO_HOST                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_LOGTO_FILE                  104
#define IDS_SOUND_MEOW                  105
#define IDS_SOUND_GLASS                 106
#define IDS_SOUND_FEAR                  107
#define IDS_SOUND_KICK                  108
#define IDS_WAVFILTER                   109
#define IDS_SOUND_SELECT                110
#define IDS_LOGFILTER                   111
#define IDS_LOG_SELECT                  112
#define IDS_LOG_EXT                     113
#define IDS_KLOGFILTER                  114
#define IDS_KLOG_EXPORT                 115
#define IDS_KLOG_IMPORT                 116
#define IDS_KLOG_EXT                    117
#define IDS_REGISTRYKEY                 118
#define IDS_KLEVERNET_URL               119
#define IDS_TIP_LOG                     120
#define IDS_LOGTIMEFORMAT               121
#define IDS_LOGPATTERN_TITLE            122
#define IDS_LOGFILETIMEFORMAT           123
#define IDS_TIP_FACILITY_ON             124
#define IDS_TIP_FACILITY_XOR            125
#define IDS_TIP_PRIORITY_ON             126
#define IDS_TIP_PRIORITY_XOR            127
#define IDR_MAINFRAME                   128
#define IDS_LOGFILEPRIFACEFORMAT        128
#define IDS_LOGFILESOURCEFORMAT         129
#define IDI_KLOG                        130
#define IDS_LOGHOSTSOURCEFORMAT         130
#define IDI_KLOG_TRIGGERED              131
#define IDS_MSG_LOOKUPFAILED            131
#define IDS_MSG_FAILEDTOEXPORT          132
#define IDS_MSG_FAILEDTOIMPORT          133
#define IDS_MSG_FAILEDTOSTORE           134
#define IDW_SOUND_MEOW                  137
#define IDW_SOUND_GLASS                 138
#define IDW_SOUND_FEAR                  139
#define IDI_PREPLAY                     140
#define IDW_SOUND_KICK                  140
#define IDI_BROWSE                      141
#define IDB_BACKGROUND                  141
#define IDD_LOG_UNIX                    143
#define IDD_LOG_RESERVED                144
#define IDI_LOGPATTERN                  144
#define IDD_LOG_LOCAL                   145
#define IDD_WARNBLOCKING                146
#define IDC_TABS                        1001
#define IDC_ADD                         1002
#define IDC_REMOVE                      1003
#define IDC_EXIT                        1004
#define IDC_TYPE_FILE                   1005
#define IDC_TYPE_HOST                   1006
#define IDC_TYPE_NONE                   1007
#define IDC_HOSTORFILE                  1008
#define IDC_HOSTFILE                    1009
#define IDC_BROWSE                      1010
#define IDC_DESC                        1011
#define IDC_FACILITY                    1017
#define IDC_EMERG                       1018
#define IDC_ALERT                       1019
#define IDC_CRIT                        1020
#define IDC_ERR                         1021
#define IDC_WARNING                     1022
#define IDC_WARN_ON                     1022
#define IDC_NOTICE                      1023
#define IDC_WARN_XOR                    1023
#define IDC_INFO                        1024
#define IDC_DEBUG                       1025
#define IDC_BROWSESOUND                 1027
#define IDC_SOUND                       1028
#define IDC_LOG                         1029
#define IDC_PLAYSOUND                   1030
#define IDC_ALL                         1031
#define IDC_NONE                        1032
#define IDC_HOSTS                       1034
#define IDC_HL_IP                       1035
#define IDC_HL_MASK                     1036
#define IDC_HL_ADD                      1037
#define IDC_HL_REMOVE                   1038
#define IDC_INVERT                      1040
#define IDC_LOGLENSPIN                  1047
#define IDC_LOGLENGTH                   1048
#define IDC_FILES                       1052
#define IDC_KLEVERNET                   1053
#define IDC_STATIC_LOGLENGTH            1054
#define IDC_EMERG_ON                    1058
#define IDC_ALERT_ON                    1059
#define IDC_CRIT_ON                     1060
#define IDC_ERR_ON                      1061
#define IDC_NOTICE_ON                   1062
#define IDC_INFO_ON                     1063
#define IDC_DEBUG_ON                    1064
#define IDC_KERNEL_ON                   1065
#define IDC_USER_ON                     1066
#define IDC_MAIL_ON                     1067
#define IDC_DAEMON_ON                   1068
#define IDC_AUTH_ON                     1069
#define IDC_SYSLOG_ON                   1070
#define IDC_LPR_ON                      1071
#define IDC_NEWS_ON                     1072
#define IDC_UUCP_ON                     1073
#define IDC_CRON_ON                     1074
#define IDC_KERNEL_EMERG                1075
#define IDC_NOTICE_XOR                  1076
#define IDC_INFO_XOR                    1077
#define IDC_DEBUG_XOR                   1078
#define IDC_KERNEL_XOR                  1079
#define IDC_KERNEL_ALERT                1080
#define IDC_KERNEL_CRIT                 1081
#define IDC_KERNEL_ERR                  1082
#define IDC_KERNEL_WARN                 1083
#define IDC_KERNEL_NOTICE               1084
#define IDC_KERNEL_INFO                 1085
#define IDC_KERNEL_DEBUG                1086
#define IDC_USER_EMERG                  1087
#define IDC_USER_ALERT                  1088
#define IDC_USER_CRIT                   1089
#define IDC_USER_ERR                    1090
#define IDC_USER_WARN                   1091
#define IDC_USER_NOTICE                 1092
#define IDC_USER_INFO                   1093
#define IDC_USER_DEBUG                  1094
#define IDC_MAIL_EMERG                  1095
#define IDC_MAIL_ALERT                  1096
#define IDC_MAIL_CRIT                   1097
#define IDC_MAIL_ERR                    1098
#define IDC_MAIL_WARN                   1099
#define IDC_MAIL_NOTICE                 1100
#define IDC_MAIL_INFO                   1101
#define IDC_MAIL_DEBUG                  1102
#define IDC_DAEMON_EMERG                1103
#define IDC_DAEMON_ALERT                1104
#define IDC_DAEMON_CRIT                 1105
#define IDC_DAEMON_ERR                  1106
#define IDC_DAEMON_WARN                 1107
#define IDC_DAEMON_NOTICE               1108
#define IDC_DAEMON_INFO                 1109
#define IDC_DAEMON_DEBUG                1110
#define IDC_AUTH_EMERG                  1111
#define IDC_AUTH_ALERT                  1112
#define IDC_AUTH_CRIT                   1113
#define IDC_AUTH_ERR                    1114
#define IDC_AUTH_WARN                   1115
#define IDC_AUTH_NOTICE                 1116
#define IDC_AUTH_INFO                   1117
#define IDC_AUTH_DEBUG                  1118
#define IDC_SYSLOG_EMERG                1119
#define IDC_SYSLOG_ALERT                1120
#define IDC_SYSLOG_CRIT                 1121
#define IDC_SYSLOG_ERR                  1122
#define IDC_SYSLOG_WARN                 1123
#define IDC_SYSLOG_NOTICE               1124
#define IDC_SYSLOG_INFO                 1125
#define IDC_SYSLOG_DEBUG                1126
#define IDC_LPR_EMERG                   1127
#define IDC_LPR_ALERT                   1128
#define IDC_LPR_CRIT                    1129
#define IDC_LPR_ERR                     1130
#define IDC_LPR_WARN                    1131
#define IDC_LPR_NOTICE                  1132
#define IDC_LPR_INFO                    1133
#define IDC_LPR_DEBUG                   1134
#define IDC_NEWS_EMERG                  1135
#define IDC_NEWS_ALERT                  1136
#define IDC_NEWS_CRIT                   1137
#define IDC_NEWS_ERR                    1138
#define IDC_NEWS_WARN                   1139
#define IDC_NEWS_NOTICE                 1140
#define IDC_NEWS_INFO                   1141
#define IDC_NEWS_DEBUG                  1142
#define IDC_UUCP_EMERG                  1143
#define IDC_UUCP_ALERT                  1144
#define IDC_UUCP_CRIT                   1145
#define IDC_UUCP_ERR                    1146
#define IDC_UUCP_WARN                   1147
#define IDC_UUCP_NOTICE                 1148
#define IDC_UUCP_INFO                   1149
#define IDC_UUCP_DEBUG                  1150
#define IDC_CRON_EMERG                  1151
#define IDC_CRON_ALERT                  1152
#define IDC_CRON_CRIT                   1153
#define IDC_CRON_ERR                    1154
#define IDC_CRON_WARN                   1155
#define IDC_CRON_NOTICE                 1156
#define IDC_CRON_INFO                   1157
#define IDC_CRON_DEBUG                  1158
#define IDC_EMERG_XOR                   1159
#define IDC_ALERT_XOR                   1160
#define IDC_CRIT_XOR                    1161
#define IDC_ERR_XOR                     1162
#define IDC_USER_XOR                    1163
#define IDC_MAIL_XOR                    1164
#define IDC_DAEMON_XOR                  1165
#define IDC_AUTH_XOR                    1166
#define IDC_SYSLOG_XOR                  1167
#define IDC_LPR_XOR                     1168
#define IDC_NEWS_XOR                    1169
#define IDC_UUCP_XOR                    1170
#define IDC_CRON_XOR                    1171
#define IDC_R0_ON                       1172
#define IDC_AUTHPRIV_ON                 1172
#define IDC_R1_ON                       1173
#define IDC_AUTHPRIV_EMERG              1173
#define IDC_R2_ON                       1174
#define IDC_AUTHPRIV_ALERT              1174
#define IDC_R3_ON                       1175
#define IDC_AUTHPRIV_CRIT               1175
#define IDC_R4_ON                       1176
#define IDC_AUTHPRIV_ERR                1176
#define IDC_R0_XOR                      1177
#define IDC_AUTHPRIV_WARN               1177
#define IDC_R1_XOR                      1178
#define IDC_AUTHPRIV_NOTICE             1178
#define IDC_R2_XOR                      1179
#define IDC_AUTHPRIV_INFO               1179
#define IDC_R3_XOR                      1180
#define IDC_AUTHPRIV_DEBUG              1180
#define IDC_R4_XOR                      1181
#define IDC_R0_EMERG                    1182
#define IDC_AUTHPRIV_XOR                1182
#define IDC_R0_ALERT                    1183
#define IDC_R0_CRIT                     1184
#define IDC_R0_ERR                      1185
#define IDC_R0_WARN                     1186
#define IDC_R0_NOTICE                   1187
#define IDC_R0_INFO                     1188
#define IDC_R0_DEBUG                    1189
#define IDC_R1_EMERG                    1190
#define IDC_R1_ALERT                    1191
#define IDC_R1_CRIT                     1192
#define IDC_R1_ERR                      1193
#define IDC_R1_WARN                     1194
#define IDC_R1_NOTICE                   1195
#define IDC_R1_INFO                     1196
#define IDC_R1_DEBUG                    1197
#define IDC_R2_EMERG                    1198
#define IDC_R2_ALERT                    1199
#define IDC_R2_CRIT                     1200
#define IDC_R2_ERR                      1201
#define IDC_R2_WARN                     1202
#define IDC_R2_NOTICE                   1203
#define IDC_R2_INFO                     1204
#define IDC_R2_DEBUG                    1205
#define IDC_R3_EMERG                    1206
#define IDC_R3_ALERT                    1207
#define IDC_R3_CRIT                     1208
#define IDC_R3_ERR                      1209
#define IDC_R3_WARN                     1210
#define IDC_R3_NOTICE                   1211
#define IDC_R3_INFO                     1212
#define IDC_R3_DEBUG                    1213
#define IDC_R4_EMERG                    1214
#define IDC_R4_ALERT                    1215
#define IDC_R4_CRIT                     1216
#define IDC_R4_ERR                      1217
#define IDC_R4_WARN                     1218
#define IDC_R4_NOTICE                   1219
#define IDC_R4_INFO                     1220
#define IDC_R4_DEBUG                    1221
#define IDC_L0_ON                       1222
#define IDC_L1_ON                       1223
#define IDC_L2_ON                       1224
#define IDC_L3_ON                       1225
#define IDC_L4_ON                       1226
#define IDC_L5_ON                       1227
#define IDC_L6_ON                       1228
#define IDC_L7_ON                       1229
#define IDC_L0_XOR                      1230
#define IDC_L1_XOR                      1231
#define IDC_L2_XOR                      1232
#define IDC_L3_XOR                      1233
#define IDC_L4_XOR                      1234
#define IDC_L5_XOR                      1235
#define IDC_L6_XOR                      1236
#define IDC_L7_XOR                      1237
#define IDC_L0_EMERG                    1238
#define IDC_L0_ALERT                    1239
#define IDC_L0_CRIT                     1240
#define IDC_L0_ERR                      1241
#define IDC_L0_WARN                     1242
#define IDC_L0_NOTICE                   1243
#define IDC_L0_INFO                     1244
#define IDC_L0_DEBUG                    1245
#define IDC_L1_EMERG                    1246
#define IDC_L1_ALERT                    1247
#define IDC_L1_CRIT                     1248
#define IDC_L1_ERR                      1249
#define IDC_L1_WARN                     1250
#define IDC_L1_NOTICE                   1251
#define IDC_L1_INFO                     1252
#define IDC_L1_DEBUG                    1253
#define IDC_L2_EMERG                    1254
#define IDC_L2_ALERT                    1255
#define IDC_L2_CRIT                     1256
#define IDC_L2_ERR                      1257
#define IDC_L2_WARN                     1258
#define IDC_L2_NOTICE                   1259
#define IDC_L2_INFO                     1260
#define IDC_L2_DEBUG                    1261
#define IDC_L3_EMERG                    1262
#define IDC_L3_ALERT                    1263
#define IDC_L3_CRIT                     1264
#define IDC_L3_ERR                      1265
#define IDC_L3_WARN                     1266
#define IDC_L3_NOTICE                   1267
#define IDC_L3_INFO                     1268
#define IDC_L3_DEBUG                    1269
#define IDC_L4_EMERG                    1270
#define IDC_L4_ALERT                    1271
#define IDC_L4_CRIT                     1272
#define IDC_L4_ERR                      1273
#define IDC_L4_WARN                     1274
#define IDC_L4_NOTICE                   1275
#define IDC_L4_INFO                     1276
#define IDC_L4_DEBUG                    1277
#define IDC_L5_EMERG                    1278
#define IDC_L5_ALERT                    1279
#define IDC_L5_CRIT                     1280
#define IDC_L5_ERR                      1281
#define IDC_L5_WARN                     1282
#define IDC_L5_NOTICE                   1283
#define IDC_L5_INFO                     1284
#define IDC_L5_DEBUG                    1285
#define IDC_L6_EMERG                    1286
#define IDC_L6_ALERT                    1287
#define IDC_L6_CRIT                     1288
#define IDC_L6_ERR                      1289
#define IDC_L6_WARN                     1290
#define IDC_L6_NOTICE                   1291
#define IDC_L6_INFO                     1292
#define IDC_L6_DEBUG                    1293
#define IDC_L7_EMERG                    1294
#define IDC_L7_ALERT                    1295
#define IDC_L7_CRIT                     1296
#define IDC_L7_ERR                      1297
#define IDC_L7_WARN                     1298
#define IDC_L7_NOTICE                   1299
#define IDC_L7_INFO                     1300
#define IDC_L7_DEBUG                    1301
#define IDC_LOGPATTERN                  1302
#define IDC_WARNBLOCKING                1303
#define ID_FILES_EXPORT                 32771
#define ID_FILES_IMPORT                 32772
#define ID_FILES_RESET                  32773
#define ID_TRAY_SHOWKLOGWINDOW          32774
#define ID_TRAY_HELP                    32776
#define ID_TRAY_ABOUTKLOG               32777
#define ID_TRAY_EXIT                    32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1304
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
